In [7]:
import numpy as np
sensor_temps = np.array([
 [72, 70, 71], # Day 1
 [75, 73, 74], # Day 2
 [68, 67, 69], # Day 3
 [71, 70, 72], # Day 4
 [74, 72, 73] # Day 5
])
print(sensor_temps)
print(f"Shape: {sensor_temps.shape}")

[[72 70 71]
 [75 73 74]
 [68 67 69]
 [71 70 72]
 [74 72 73]]
Shape: (5, 3)


In [11]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

2


In [12]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [13]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.size)

6


In [14]:
arr = np.array([1.5, 2.7, 3.2])
print(arr.dtype)

float64


In [15]:
arr = np.array([1,2,3])
print(arr.itemsize)

8


In [17]:
crops = np.array(['corn', 'wheat', 'soy', 'barley', 'oats'])
print(crops[0])
print(crops[-1])
print(crops[1:4])
print(crops[::2])
print(crops[1])

corn
oats
['wheat' 'soy' 'barley']
['corn' 'soy' 'oats']
wheat


In [18]:
ph_levels = np.array([
 [6.5, 6.8, 6.3, 6.7],
 [7.1, 7.0, 6.9, 7.2],
 [6.2, 6.4, 6.1, 6.3]
])
print(ph_levels[1, 2])
print(ph_levels[0, :])
print(ph_levels[:, 3])


6.9
[6.5 6.8 6.3 6.7]
[6.7 7.2 6.3]


In [19]:
sub_array = ph_levels[0:2, 0:3]
print(sub_array)
print(ph_levels[::2, :])

[[6.5 6.8 6.3]
 [7.1 7.  6.9]]
[[6.5 6.8 6.3 6.7]
 [6.2 6.4 6.1 6.3]]
