In [11]:
import numpy as np
sensor_temps = np.array([
 [72, 70, 71],
 [75, 73, 74],
 [68, 67, 69],
 [71, 70, 72],
 [74, 72, 73]
])
zeros = np.zeros((5, 3))
print(sensor_temps)
print(f"Shape: {sensor_temps.shape}")

[[72 70 71]
 [75 73 74]
 [68 67 69]
 [71 70 72]
 [74 72 73]]
Shape: (5, 3)


In [12]:
import numpy as np
sensor_temps = np.array([
 [72, 70, 71],
 [75, 73, 74],
 [68, 67, 69],
 [71, 70, 72],
 [74, 72, 73]
])
identity = np.eye(3)
print(sensor_temps)
print(f"Shape: {sensor_temps.shape}")

[[72 70 71]
 [75 73 74]
 [68 67 69]
 [71 70 72]
 [74 72 73]]
Shape: (5, 3)


In [13]:
import numpy as np
sensor_temps = np.array([
 [72, 70, 71],
 [75, 73, 74],
 [68, 67, 69],
 [71, 70, 72],
 [74, 72, 73]
])
sequence = np.arange(0, 10, 2)
print(sensor_temps)
print(f"Shape: {sensor_temps.shape}")

[[72 70 71]
 [75 73 74]
 [68 67 69]
 [71 70 72]
 [74 72 73]]
Shape: (5, 3)


In [14]:
import numpy as np
sensor_temps = np.array([
 [72, 70, 71],
 [75, 73, 74],
 [68, 67, 69],
 [71, 70, 72],
 [74, 72, 73]
])
linspace = np.linspace(0, 100, 5)
print(sensor_temps)
print(f"Shape: {sensor_temps.shape}")

[[72 70 71]
 [75 73 74]
 [68 67 69]
 [71 70 72]
 [74 72 73]]
Shape: (5, 3)


In [17]:
temperatures = np.array([72, 85, 91, 68, 95, 70, 88])
hot_days = temperatures > 85
print(hot_days)
print(temperatures[hot_days])
print(temperatures[temperatures > 85])


[False False  True False  True False  True]
[91 95 88]
[91 95 88]


In [18]:
moderate = temperatures[(temperatures >= 70) &
(temperatures <= 85)]
print(moderate)

[72 85 70]


In [19]:
extreme = temperatures[(temperatures > 90) |
(temperatures < 70)]
print(extreme)

[91 68 95]


In [20]:
field_a = np.array([120, 135, 142, 128])
field_b = np.array([118, 140, 138,132])
total_yield = field_a + field_b
print(total_yield)
difference = field_a - field_b
print(difference)
doubled = field_a * 2
print(doubled)

[238 275 280 260]
[ 2 -5  4 -4]
[240 270 284 256]


In [22]:
field_a = np.array([120, 135, 142, 128])
field_b = np.array([118, 140, 138,132])
total_yield = field_a + field_b
print(total_yield)
result = []
for i in range(len(field_a)):
 result.append(field_a[i] + field_b[i])

[238 275 280 260]


In [28]:
daily_rainfall = np.array([0.2, 0.0, 0.5, 1.2, 0.3, 0.1, 0.0])
total = np.sum(daily_rainfall)
print(total)


2.3


In [44]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

2


In [31]:
arr = np.array([1, 2, 3, 4, 5])
slice_view = arr[1:4]
slice_view[0] = 999
print(arr)

[  1 999   3   4   5]


In [43]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [40]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.size)

6


In [41]:
arr = np.array([1.5, 2.7, 3.2])
print(arr.dtype)

float64


In [42]:
arr = np.array([1,2,3])
print(arr.itemsize)

8


In [39]:
crops = np.array(['corn', 'wheat', 'soy', 'barley', 'oats'])
print(crops[0])
print(crops[-1])
print(crops[2])
print(crops[1])
print(crops[3])
print(crops[1:4])
print(crops[::2])
print(crops[1])

corn
oats
soy
wheat
barley
['wheat' 'soy' 'barley']
['corn' 'soy' 'oats']
wheat


In [38]:
ph_levels = np.array([
 [6.5, 6.8, 6.3, 6.7],
 [7.1, 7.0, 6.9, 7.2],
 [6.2, 6.4, 6.1, 6.3]
])
print(ph_levels[1, 2])
print(ph_levels[0, :])
print(ph_levels[:, 3])


6.9
[6.5 6.8 6.3 6.7]
[6.7 7.2 6.3]


In [45]:
sub_array = ph_levels[0:2, 0:3]
print(sub_array)
print(ph_levels[::2, :])

[[6.5 6.8 6.3]
 [7.1 7.  6.9]]
[[6.5 6.8 6.3 6.7]
 [6.2 6.4 6.1 6.3]]


In [52]:
import numpy as np
ph_levels = np.array([
 [6.5, 6.8, 6.3, 6.7],
 [7.1, 7.0, 6.9, 7.2],
 [6.2, 6.4, 6.1, 6.3]
])
sub_array = ph_levels[0:3, 0:4]
print(sub_array)
print(ph_levels[0, :3])

[[6.5 6.8 6.3 6.7]
 [7.1 7.  6.9 7.2]
 [6.2 6.4 6.1 6.3]]
[6.5 6.8 6.3]
